on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: |
          8.0.x
          10.0.x
    - name: Build Library
      run: dotnet build --configuration Release ConsoleMarkdownRenderer.csproj
    - name: Build Fakes
      run: dotnet build --configuration Release ConsoleMarkdownRenderer.Fakes
    - name: Build Example
      run: dotnet build --configuration Release ConsoleMarkdownRenderer.Example
    - name: Test
      run: dotnet test --configuration Release ConsoleMarkdownRenderer.Tests
    - name: Test ExampleTests
      run: dotnet test --configuration Release ConsoleMarkdownRenderer.ExampleTests
