on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Build
      run: dotnet build
    - name: Test
      run: dotnet test ConsoleMarkdownRenderer.Tests /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
    - name: Upload Code Coverage
      uses: codecov/codecov-action@v2
      with:
        files: ./ConsoleMarkdownRenderer.Tests/coverage.opencover.xml
        name: codecov-umbrella # optional
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)
        token: ${{ secrets.CODECOV_TOKEN }}