name: NuGet Pack Test
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number for the packages (e.g., 0.7.14)'
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 0
    - name: Set VERSION variable
      run: echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
    - name: Build
      run: dotnet build --configuration Release /p:Version=${VERSION} ConsoleMarkdownRenderer.csproj
    - name: Test
      run: dotnet test --configuration Release /p:Version=${VERSION} ConsoleMarkdownRenderer.Tests
    - name: Build Example
      run: dotnet build --configuration Release /p:Version=${VERSION} ConsoleMarkdownRenderer.Example
    - name: Pack
      run: dotnet pack --configuration Release /p:Version=${VERSION} --no-build --output ./artifacts ConsoleMarkdownRenderer.csproj
    - name: Add local NuGet source
      run: dotnet nuget add source "$GITHUB_WORKSPACE/artifacts" --name local
    - name: Build Fakes
      run: dotnet build --configuration Release /p:Version=${VERSION} /p:UsePackageReference=true ConsoleMarkdownRenderer.Fakes
    - name: Pack Fakes
      run: dotnet pack --configuration Release /p:Version=${VERSION} /p:UsePackageReference=true --no-build --output ./artifacts ConsoleMarkdownRenderer.Fakes
    - name: Test ExampleTests
      run: dotnet test --configuration Release /p:Version=${VERSION} ConsoleMarkdownRenderer.ExampleTests
