# Created from https://acraven.medium.com/a-nuget-package-workflow-using-github-actions-7da8c6557863
on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - name: Verify commit exists in origin/main
      run: git branch --remote --contains | grep origin/main
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Build
      run: dotnet build --configuration Release /p:Version=${VERSION} ConsoleMarkdownRenderer.csproj
    - name: Test
      run: dotnet test --configuration Release /p:Version=${VERSION} ConsoleMarkdownRenderer.Tests/ConsoleMarkdownRenderer.Tests.csproj
    - name: Pack
      run: dotnet pack --configuration Release /p:Version=${VERSION} --no-build --output . ConsoleMarkdownRenderer.csproj
    - name: Push
      run: dotnet nuget push BoxOfYellow.ConsoleMarkdownRenderer.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${API_KEY}
      env:
        API_KEY: ${{ secrets.NUGET_API_KEY }}